name: hashicars
description: "Car sales website"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-196.1.beta

dependencies:
  cloud_firestore: ^5.6.12
  firebase_core: ^3.15.2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.3
  google_maps_flutter_web: ^0.5.12+2
  phosphor_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    -  assets/images/