import 'package:flutter/material.dart';
import 'package:hashicars/pages/vehicles/carCard.dart';

class Vehicles extends StatelessWidget {
  const Vehicles({super.key});

  @override
  Widget build(BuildContext context) {
    final List<Car> dummyCars = [
  Car(
    id: '1',
    make: 'Tesla',
    model: 'Model S',
    year: 2022,
    price: 89990,
    imageUrl: 'https://cdn.motor1.com/images/mgl/7e8Qo/s1/tesla-model-s-plaid.jpg',
    location: 'San Francisco, CA',
    mileage: 2500,
    transmission: 'Automatic',
    fuelType: 'Electric',
    horsepower: 1020,
    color: 'Red',
    rating: 4.9,
  ),
  Car(
    id: '2',
    make: 'Ford',
    model: 'Mustang GT',
    year: 2021,
    price: 42990,
    imageUrl: 'https://cdn.motor1.com/images/mgl/6bq4N/s1/2021-ford-mustang-mach-1.jpg',
    location: 'Austin, TX',
    mileage: 12500,
    transmission: 'Manual',
    fuelType: 'Gasoline',
    horsepower: 450,
    color: 'Blue',
    rating: 4.7,
  ),
  Car(
    id: '3',
    make: 'Toyota',
    model: 'Camry XSE',
    year: 2023,
    price: 32990,
    imageUrl: 'https://cdn.motor1.com/images/mgl/9MOX2/s1/2023-toyota-camry.jpg',
    location: 'Chicago, IL',
    mileage: 500,
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    horsepower: 208,
    color: 'White',
    rating: 4.5,
  ),
  Car(
    id: '4',
    make: 'BMW',
    model: 'M3 Competition',
    year: 2022,
    price: 72900,
    imageUrl: 'https://cdn.motor1.com/images/mgl/0x0X3/s1/bmw-m3-competition.jpg',
    location: 'Miami, FL',
    mileage: 8000,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    horsepower: 503,
    color: 'Black',
    rating: 4.8,
  ),
  Car(
    id: '5',
    make: 'Honda',
    model: 'Civic Type R',
    year: 2023,
    price: 43990,
    imageUrl: 'https://cdn.motor1.com/images/mgl/9MOX2/s1/2023-honda-civic-type-r.jpg',
    location: 'Seattle, WA',
    mileage: 3000,
    transmission: 'Manual',
    fuelType: 'Gasoline',
    horsepower: 315,
    color: 'Championship White',
    rating: 4.6,
  ),
  Car(
    id: '6',
    make: 'Porsche',
    model: '911 Turbo S',
    year: 2022,
    price: 203500,
    imageUrl: 'https://cdn.motor1.com/images/mgl/0x0X3/s1/porsche-911-turbo-s.jpg',
    location: 'Beverly Hills, CA',
    mileage: 3500,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    horsepower: 640,
    color: 'GT Silver',
    rating: 4.9,
  ),
  Car(
    id: '7',
    make: 'Jeep',
    model: 'Wrangler Rubicon',
    year: 2021,
    price: 45995,
    imageUrl: 'https://cdn.motor1.com/images/mgl/6bq4N/s1/jeep-wrangler-rubicon-392.jpg',
    location: 'Denver, CO',
    mileage: 18500,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    horsepower: 285,
    color: 'Sarge Green',
    rating: 4.4,
  ),
  Car(
    id: '8',
    make: 'Audi',
    model: 'RS6 Avant',
    year: 2023,
    price: 109000,
    imageUrl: 'https://cdn.motor1.com/images/mgl/9MOX2/s1/audi-rs6-avant.jpg',
    location: 'New York, NY',
    mileage: 2500,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    horsepower: 591,
    color: 'Nardo Gray',
    rating: 4.8,
  ),
  Car(
    id: '9',
    make: 'Subaru',
    model: 'WRX STI',
    year: 2021,
    price: 37995,
    imageUrl: 'https://cdn.motor1.com/images/mgl/6bq4N/s1/subaru-wrx-sti-final-edition.jpg',
    location: 'Portland, OR',
    mileage: 14200,
    transmission: 'Manual',
    fuelType: 'Gasoline',
    horsepower: 310,
    color: 'World Rally Blue',
    rating: 4.5,
  ),
  Car(
    id: '10',
    make: 'Mercedes-Benz',
    model: 'AMG GT',
    year: 2022,
    price: 131400,
    imageUrl: 'https://cdn.motor1.com/images/mgl/0x0X3/s1/mercedes-amg-gt-black-series.jpg',
    location: 'Dallas, TX',
    mileage: 6000,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    horsepower: 720,
    color: 'Sun Yellow',
    rating: 4.9,
  ),
  Car(
    id: '11',
    make: 'Chevrolet',
    model: 'Corvette Stingray',
    year: 2023,
    price: 64995,
    imageUrl: 'https://cdn.motor1.com/images/mgl/9MOX2/s1/2023-chevrolet-corvette-stingray.jpg',
    location: 'Detroit, MI',
    mileage: 1500,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    horsepower: 495,
    color: 'Red Mist',
    rating: 4.8,
  ),
  Car(
    id: '12',
    make: 'Land Rover',
    model: 'Defender',
    year: 2022,
    price: 54975,
    imageUrl: 'https://cdn.motor1.com/images/mgl/0x0X3/s1/land-rover-defender-v8.jpg',
    location: 'Salt Lake City, UT',
    mileage: 9500,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    horsepower: 395,
    color: 'Santorini Black',
    rating: 4.6,
  ),
  Car(
    id: '13',
    make: 'Lexus',
    model: 'LC 500',
    year: 2023,
    price: 94950,
    imageUrl: 'https://cdn.motor1.com/images/mgl/9MOX2/s1/lexus-lc-500.jpg',
    location: 'Atlanta, GA',
    mileage: 2000,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    horsepower: 471,
    color: 'Structural Blue',
    rating: 4.7,
  ),
  Car(
    id: '14',
    make: 'Dodge',
    model: 'Challenger Hellcat',
    year: 2022,
    price: 65995,
    imageUrl: 'https://cdn.motor1.com/images/mgl/0x0X3/s1/dodge-challenger-srt-hellcat.jpg',
    location: 'Las Vegas, NV',
    mileage: 7500,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    horsepower: 717,
    color: 'F8 Green',
    rating: 4.7,
  ),
  Car(
    id: '15',
    make: 'Volkswagen',
    model: 'Golf R',
    year: 2023,
    price: 44995,
    imageUrl: 'https://cdn.motor1.com/images/mgl/9MOX2/s1/volkswagen-golf-r.jpg',
    location: 'Boston, MA',
    mileage: 3000,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    horsepower: 315,
    color: 'Lapiz Blue',
    rating: 4.5,
  ),
  Car(
    id: '16',
    make: 'Ferrari',
    model: 'Portofino M',
    year: 2022,
    price: 218750,
    imageUrl: 'https://cdn.motor1.com/images/mgl/0x0X3/s1/ferrari-portofino-m.jpg',
    location: 'Newport Beach, CA',
    mileage: 4500,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    horsepower: 612,
    color: 'Rosso Corsa',
    rating: 4.9,
  ),
  Car(
    id: '17',
    make: 'Hyundai',
    model: 'Santa Fe Calligraphy',
    year: 2023,
    price: 42950,
    imageUrl: 'https://cdn.motor1.com/images/mgl/9MOX2/s1/hyundai-santa-fe-calligraphy.jpg',
    location: 'Phoenix, AZ',
    mileage: 2500,
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    horsepower: 277,
    color: 'Phantom Black',
    rating: 4.4,
  ),
  Car(
    id: '18',
    make: 'Mazda',
    model: 'MX-5 Miata',
    year: 2022,
    price: 31950,
    imageUrl: 'https://cdn.motor1.com/images/mgl/0x0X3/s1/mazda-mx-5-miata.jpg',
    location: 'San Diego, CA',
    mileage: 8500,
    transmission: 'Manual',
    fuelType: 'Gasoline',
    horsepower: 181,
    color: 'Soul Red Crystal',
    rating: 4.6,
  ),
  Car(
    id: '19',
    make: 'Lamborghini',
    model: 'Huracán EVO',
    year: 2022,
    price: 261274,
    imageUrl: 'https://cdn.motor1.com/images/mgl/0x0X3/s1/lamborghini-huracan-evo.jpg',
    location: 'Miami Beach, FL',
    mileage: 5000,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    horsepower: 631,
    color: 'Arancio Borealis',
    rating: 4.9,
  ),
  Car(
    id: '20',
    make: 'Kia',
    model: 'Telluride',
    year: 2023,
    price: 43990,
    imageUrl: 'https://cdn.motor1.com/images/mgl/9MOX2/s1/kia-telluride.jpg',
    location: 'Nashville, TN',
    mileage: 4000,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    horsepower: 291,
    color: 'Everlasting Silver',
    rating: 4.5,
  ),
];
    return  Scaffold(
      body: ListView.builder(
  itemCount: dummyCars.length,
  itemBuilder: (context, index) {
    final car = dummyCars[index];
    return Card(
      margin: EdgeInsets.all(8),
      elevation: 4,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Car Image
          ClipRRect(
            borderRadius: BorderRadius.vertical(top: Radius.circular(12)),
            child: Image.network(
              car.imageUrl,
              height: 180,
              width: double.infinity,
              fit: BoxFit.cover,
              errorBuilder: (context, error, stackTrace) => Container(
                height: 180,
                color: Colors.grey[300],
                child: Icon(Icons.car_repair, size: 50),
              ),
            ),
          ),
          
          // Car Details
          Padding(
            padding: EdgeInsets.all(12),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  car.fullName,
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                SizedBox(height: 4),
                Row(
                  children: [
                    Icon(Icons.location_on, size: 16, color: Colors.grey),
                    SizedBox(width: 4),
                    Text(car.location),
                  ],
                ),
                SizedBox(height: 8),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('${car.mileage.toStringAsFixed(0)} miles'),
                        Text('${car.transmission} • ${car.fuelType}'),
                      ],
                    ),
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.end,
                      children: [
                        Text(
                          car.formattedPrice,
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                            color: Colors.blue,
                          ),
                        ),
                        Row(
                          children: [
                            Icon(Icons.star, color: Colors.amber, size: 16),
                            Text(car.rating.toString()),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  },
),
    );
  }
}